version: '3'

services:
    influxdb:
        image: influxdb:latest
        container_name: influxdb
        ports:
            - '8083:8083'
            - '8086:8086'
            - '8090:8090'
            - '2003:2003'
        env_file:
            - '.env'
        volumes:
            - ./influxdb/data:/var/lib/influxdb
